### ISSUE TITLE
Extensions of primitive values are not supported

### ISSUE THREAD

**Issue by julian-r** [skalarsystems/fhirzeug#13]
https://www.hl7.org/fhir/json.html#primitive

**Comment by Wauplin** [comment]
I started to look at this problem which brought me to dive more into the FHIR documentation. For what I understand, (almost) every element of a Resource can be extended at run time with an `Extension` object we don't necessarily know about before receving the resource. This means that we need to find a way to receive and validate those extensions. 

An example of resource using extension in `activitydefinition-example.json` :
```json
{
  "resourceType": "ActivityDefinition",
  "id": "referralPrimaryCareMentalHealth",
  
  (...)
  
  "timingTiming": {
    "_event": [
      {
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/cqf-expression",
            "valueExpression": {
              "language": "text/cql",
              "expression": "Now()"
            }
          }
        ]
      }
    ]
  },
  
  (...)
}
```

In this example, `event` should have been a list of datetimes as defined in the following `Timing` class :
```py
class Timing(BackboneElement):
    (...)
    event: typing.Optional[typing.List["FHIRDateTime"]]
    repeat: typing.Optional["TimingRepeat"]
    code: typing.Optional["CodeableConcept"]
```

I also noticed in the documentation that it is possible for an element to be described by both a "normal" and an "extended" value (even if we don't have such examples in our tests yet). Example from https://www.hl7.org/fhir/json.html#primitive :
```json
"code": [ "au", "nz" ],
"_code": [
  null,
  {
    "extension" : [ 
      {
        "url" : "http://hl7.org/fhir/StructureDefinition/display",
        "valueString" : "New Zealand a.k.a Kiwiland"
      }
    ]
  }
]
```

**Possible solution ?**
A beginning of a solution could be to store/validate both "normal" and "extended" attributes in every classes. I tested it by adding this code in `resource.py.jinja2` : 

```jinja2
    {%- set extension_type_name = "\"Extension\"" %}
    {%- if prop.is_array %}
       {%- set extension_type_name = "typing.List[typing.Optional({})]".format(extension_type_name) %}
    {%- endif %}
    {%- set extension_type_name = "typing.Optional[{}]".format(extension_type_name) %}
    _{{ prop.name | snake_case }}: {{ extension_type_name }}
```
Which results in a class definition like this :
```py
class Timing(BackboneElement):
   (...)
    event: typing.Optional[typing.List["FHIRDateTime"]]
    _event: typing.Optional[typing.List[typing.Optional["Extension"]]]

    repeat: typing.Optional["TimingRepeat"]
    _repeat: typing.Optional["Extension"]

    code: typing.Optional["CodeableConcept"]
    _code: typing.Optional["Extension"]
```

Problems that I see with this solution :
- it requires to modify pydantic behavior to allow attributes starting by a underscore. This is done in the metamodel definition : https://github.com/samuelcolvin/pydantic/blob/0698384788e78b3353877bc44340a00089ea1d3f/pydantic/main.py#L121 . Not sure how to do it in a pythonic way. Maybe we could change naming with for instance attribute `event` and attribute `event_extended` (instead of `_event`). However, this could lead to naming conflicts (that can be easily detected when packaging the code).
- it also requires to change the dict pre/post processing (at the same place of `_without_empty_items`) in order to ease validation. For example : `"_event": [ {"extension": [{(..)}]} ]` -> `"_event": [ {[{(..)}]} ]` since "extension" seems to be a redundant information after the underscore. 
- and finally, this might complicate the use of the objects in a server since each attribute access will require to check both at the "normal" and the "extended" attributes. Don't know if we could avoid that by exposing at runtime a third property that would check both attributes and output the most relevant.


Any suggestions about this topic ? I feel that I might have missed something important.

**Comment by Wauplin** [comment]
Started again to work on this one. From what I spotted from the specification :
- primitive datatypes can be extended by prepending a "_" to the attribute name (let's call `primitive_field` and `_primitive_field` the primitive field and its extension). `_primitive_field` contains an `id` and an `extension` (both optional). I think we create a new class in `resource_footer.py` for that :
```py 
class PrimitiveExtension(Element):
    pass
```
- we can't prepend an underscore since pydantic will ignore it so we need to have in `footer_header` a method `get_primitive_extension_name(field_name:str)->str` that can be used as an alias (for example `field_name` -> `field_name__extension`). I think the double underscore is the safest way to ensure no name conflicts will appear. Also need to change `alias_generator` to use this method.
- if primitive field is a list (e.g. `typing.List[FHIRString]`) it must be changed to a list of optional field (`typing.List[typing.Optional[FHIRString]]`) and the extension must be of type `typing.Optional[typing.List[typing.Optional[PrimitiveExtension]]]`. Additional rule that must be validated is that both lists must be of same length if provided. In practice, each  primitive element can be extended.
- and last thing to check that I'm not 100% sure about, if an field is mandatory can it be only present as an extension ? If yes that would mean we need to change all primitive fields into `typing.Optional[field_type]` and then add a root_validator to check that at least one of  `primitive_field` and `_primitive_field` is not None. Same adaptation for lists.
