### ISSUE TITLE
Docstrings for enums

### ISSUE THREAD

**Issue by julian-r** [skalarsystems/fhirzeug#19]
ATM we have docstrings for enums, but they are not quite nice.

Some investigation is probalby needed how to do that in the correct way, so the schema generation of pydantic also recognizes the docstrings. What I found is:

https://stackoverflow.com/questions/52062831/how-do-i-properly-document-python-enum-elements

**Comment by behzadmehrabi** [comment]
I'm working on it. :)

**Comment by Bezmehrabi** [comment]
when I try to run:
`VisionPrescriptionLensSpecificationPrism.schema_json()`

at the end of _r4.py_ file
I get that Error:
`KeyError: <class '__main__.Quantity'>`

do you know what is the problem?

**Comment by behzadmehrabi** [comment]
[Related PR](https://github.com/skalarsystems/fhirzeug/pull/15#issue-427169604)
test `test_read_write` is failed.

I debug it and the problem is that when convert object to  json, the enum member value is empty.
**for example:**
```
>>>  VisionPrescriptionLensSpecificationPrism(amount=434, base="up").dict(by_alias=True, exclude_unset=True)

{'amount': 434.0, 'base': <VisionBase.up: 'up'>}

>>> VisionPrescriptionLensSpecificationPrism(amount=434, base="up").json(by_alias=True, exclude_unset=True)

{"amount": 434, "base": ""}
```
but if `VisionBase` enum class inherit from `enum.Enum` instead of `DocEnum`, it works fine
and returns:

`{"amount": 434, "base": "up"}`

I'm working on it but haven't figure it out yet.

**UPDATE:**
fixed.
