### ISSUE TITLE
Add More Metainformation to the Generated Resources

### ISSUE THREAD

**Issue by julian-r** [skalarsystems/fhirzeug#21]
I possible we should try to get more meta information into the generated classes: E.g.:

- Which category and level the resource belongs to.
- The Resource URL

**Comment by Wauplin** [comment]
**Idea :** add meta information to generated resources.
- catagory and level as defined here : https://www.hl7.org/fhir/ . Seems to apply only for Resources
- URL . Seems to apply to both Resources and CodeSystems. 

**Notes :**
- Meta information here doesn't refer to the Meta resource from FHIR.
- Add meta as a python-accessible class variable. Material to do this in a pydantic way : https://github.com/samuelcolvin/pydantic/issues/184 .  We do not want to validate nor serialize this information.

**Comment by Wauplin** [comment]
I investigated this issue in order to get a bigger overview of the different types of generated classes we are dealing with and what is the meta-informations we might want to retrieve. 

# Resources 

### Relevant informations

See https://www.hl7.org/fhir/resourcelist.html
- Resource `URL` : available in json. Actually, it's even an `urls` field that we need since a class can be generated for several times (see `Quantity` and `MoneyQuantity`).
- `level` : NA
- `category` : NA
- `maturity` : NA
- `security_category` : NA
- `standard_status` : NA
- `committee` : NA

=> **Do we want all of those fields ? How mandatory is it to retrieve them ?**
=> A solution to retrieve missing fields is to parse the html of this page : https://www.hl7.org/fhir/resourcelist.html . Problem : we either scrap the webpage which is dirty or either we download the full website (via : https://www.hl7.org/fhir/downloads.html ) which requires to download a zip of 200MB (1.8GB/35k files unzipped). 

### Implementation

Getting all the urls associated to a given resource class is quite straightforward. Getting the other fields requires more work (and might be more dirty). Then, we can define Metadata namedtuple that is added to every generated classes as a `_META` attribute. Pydantic doesn't serialize attributes starting with an underscore to it doesn't interfere with the serialization.

- In `resource_header.py`
```py
class FHIRSharedMetadata(typing.NamedTuple):
    urls: typing.Optional[typing.List[str]] = None
    level: typing.Optional[str] = None
    category: typing.Optional[str] = None
    maturity: typing.Optional[str] = None
    security_category: typing.Optional[str] = None
    standard_status: typing.Optional[str] = None
    committee: typing.Optional[str] = None
```

- In `r4.py`
```py
class PractitionerRole(DomainResource):
    """ Roles/organizations the practitioner is associated with.

    A specific set of Roles/Locations/specialties/services that a practitioner
    may perform at an organization for a period of time.
    """
    resource_type = "PractitionerRole"
    
    _META = FHIRSharedMetadata(
        urls=[
           "http://hl7.org/fhir/StructureDefinition/PractitionerRole",
        ],
    )

   (...)
```

# Elements / BackboneElements

Elements are classes generated to represent the attributes of resources. In practice, we generate them the exact same way we generate the resources. I think we can add the same `_META` attribute only filled with the url info. I think we will need to infer the URL based on the name. For instance, the `SubstanceNucleicAcid` resource (http://hl7.org/fhir/StructureDefinition/SubstanceNucleicAcid) has a `subunit` element ( http://hl7.org/fhir/substancenucleicacid-definitions.html#SubstanceNucleicAcid.subunit ). Or otherwise if we do not want to build an uncertain url, we can just put the URL of the Resouce since all of the information is contained in the page. This last solution is also straightforward.

# Valuesets / Codesystems

### Relevant informations

An example of JSON : http://hl7.org/fhir/valueset-account-type.json.html
- `URL` : single url per valueset. Straightforward to get from current implementation.
- `Publisher` : in the JSON (example : "FHIR Project team")
- `Committee` : web scraping (example : "Patient Administration  Work Group")
- `Source` : web scraping http://hl7.org/fhir/terminologies-valuesets.html  (example : "Internal" or "Snomed")

### Implementation :

Valuesets inherits from `(str, DocEnum)` (and `DocEnum` from  `enum.Enum`) which makes it more difficult to add meta-information to it. I'm not sure yet how to implement that. If the purpose of this issue in only for documentation, it can of course be added as a docstring.

**Comment by julian-r** [comment]
- I think we are fine if we just have the url. I would only use information which is available through JSON.
   - Scraping seems not worth the effort
- Instead of _META, would could also use the already included Meta class.
- In case of DocEnum, i don't know how to do it at the moment, but we can move this to a sperate issue. Mainly its important to have the generation of the CapabilityStatement.

**Comment by Wauplin** [comment]
PR is created for the FHIR resources.
Metadata for DocEnum will be treated in a separate issue.
