### ISSUE TITLE
Handling of numbers

### ISSUE THREAD

**Issue by julian-r** [skalarsystems/fhirzeug#47]
Numbers are truncated in several ways:
 - `0.00` turns into `0.0` for float fields
 - If a field is defined as an integer it truncates floats: `1.23` -> `1`. This is information loss and can not be tolerated in FHIR.

**Comment by Wauplin** [comment]
This is a minimal example to reproduce the two issues described above : 

```py
import r4
import decimal


data = {
    "resourceType": "DeviceMetric",
    "id": "example",
    "type": {
        "coding": [
            {
                "system": "urn:iso:std:iso:11073:10101",
                "code": "150456",
                "display": "MDC_PULS_OXIM_SAT_O2",
            }
        ]
    },
    "category": "measurement",
    "measurementPeriod": {"repeat": {"frequency": 1.234, "duration": 5.000,}},
}

resource = r4.from_dict(data)

#  First issue -> loss of precision
assert resource.measurement_period.repeat.duration == decimal.Decimal("5.0")

# Second issue -> loss of information (float is parsed to int)
assert resource.measurement_period.repeat.frequency == 1

```

I think those issues must be treated separately. Especially : 
- For first issue, it is mandatory to solve it since precision must not be lost.
- For second issue, I think we might want to raise a `ValidationError` when a float is provided instead of truncating the float number to an int.

**Note :**
The issue here is purely about pydantic and pydantic_fhir implementation. Hope that FastAPI behavior will not add another layer of issues.

**Comment by Wauplin** [comment]
This is a minimal example to reproduce issues described above : 

```py
import r4
import decimal

repeat_data = {
    "frequency": 1.234,
    "duration": "5.000",
}
repeat = r4.TimingRepeat(**repeat_data)

#  First issue -> loss of precision -> not due directly to pydantic/pydantic_fhir
# repeat.duration == decimal.Decimal("5.000")

# Second issue -> loss of information (float is parsed to int)
# repeat.frequency == 1

```

I think those issues must be treated separately. Especially : 
- For first issue, pydantic/pydantic_fhir process well decimals when provided by a string. Issue we have is very likely to come from FastAPI preprocessing ("how the json is loaded").
- For second issue, I think we might want to raise a `ValidationError` when a float is provided instead of truncating the float number to an int. A custom validator would surely work.

**Comment by Wauplin** [comment]
Even more minimal example for the first issue. Seem to come from how decimal values are treated by `jsonable_encoder`.

```py
import decimal
from fastapi.encoders import jsonable_encoder

jsonable_encoder({"value": decimal.Decimal("5.000")})
# {'value': 5.0}
```

**EDIT :** 
It is possible to change the behavior of jsonable_encoder easily. I think following code can be a good workaround to our problem. But it is not a matter of fhizeug/pydantic_fhir, but a matter of how we use it.
```py
def decimal_encoder(value):
    return str(value)


jsonable_encoder(
    {"value": decimal.Decimal("5.000")},
    custom_encoder={decimal.Decimal: decimal_encoder},
)
# {'value': '5.000'}
```

**Comment by Wauplin** [comment]
Issue has been splitted to address differently both problems.
See #50 for serialization of decimal values.
